# Generated by Django 2.2.5 on 2019-11-21 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_comment'),
        ('articles', '0002_auto_20191024_0910'),
    ]

    operations = [
    ]
