# Generated by Django 2.2.5 on 2019-11-04 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_auto_20191024_0910'),
        ('articles', '0002_comment'),
    ]

    operations = [
    ]
